import {
    defaultMotion,
    defaultRadius,
    defaultSpacing,
    defaultTypography,
} from './tokens';
import { ThemeDescriptor, ThemeEffects, ThemePalette } from './types';

const palette: ThemePalette = {
    red: '#EF4444',
    orange: '#F59E0B',
    yellow: '#FBBF24',
    green: '#22C55E',
    cyan: '#22D3EE',
    blue: '#3B82F6',
    magenta: '#A855F7',
    purple: '#A855F7',
    white: '#E8E8ED',
    fg: '#E8E8ED',
    black: '#0A0A0F',
    bg: '#0A0A0F',
    gutterGrey: '#1C1C26',
    commentGrey: '#6B6B80',
    selection: '#1E1E28',
    background: '#0A0A0F',
    foreground: '#E8E8ED',
    currentLine: '#16161E',
    comment: '#6B6B80',
};

const effects: ThemeEffects = {
    cardShadowRaised: {
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.5,
        shadowRadius: 12,
        elevation: 6,
    },
    cardShadowInset: {
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.4,
        shadowRadius: 6,
    },
    cardBorderRadius: 20,
    cardPadding: 16,
    glassBackground: 'rgba(255, 255, 255, 0.06)',
    glassBorderColor: 'rgba(255, 255, 255, 0.10)',
    glassBorderWidth: 1,
    blurIntensity: 20,
    blurTint: 'dark',
    buttonShadowRaised: {
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.4,
        shadowRadius: 8,
        elevation: 4,
    },
    buttonShadowPressed: {
        shadowColor: '#000000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    iconBgBackground: 'rgba(99, 102, 241, 0.15)',
    iconBgBorderColor: 'rgba(99, 102, 241, 0.25)',
};

export const darkMinimalTheme: ThemeDescriptor = {
    id: 'darkMinimal',
    name: 'Dark Minimal',
    variant: 'dark',
    palette: palette,
    colors: {
        attention: palette.red,
        background: palette.bg,
        icon: palette.white,
        text: palette.fg,
        fadedText: 'rgba(232, 232, 237, 0.5)',
        accent: '#6366F1',
        accentAlt: '#22D3EE',
        border: '#1C1C26',
        textSecondary: palette.commentGrey,
        textPrimary: palette.fg,
        surface: '#16161E',
        surfaceAlt: '#0E0E14',
        surfaceHighlight: '#1E1E28',
        primary: '#6366F1',
        error: palette.red,
        card: '#16161E',
        warning: palette.orange,
        success: palette.green,
        info: '#6366F1',
        calendar: '#3B82F6',
        email: '#EF4444',
        task: '#22C55E',
        codeBg: '#0E0E14',
        codeInlineBg: '#16161E',
        codeText: palette.fg,
        blockquoteBg: '#0E0E14',
        blockquoteBorder: '#6366F1',
    },
    effects,
    spacing: defaultSpacing,
    radius: defaultRadius,
    typography: defaultTypography,
    motion: defaultMotion,
};

export const darkMinimal = darkMinimalTheme.colors;
export const darkMinimalPalette = palette;
